### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by natewallace** [unumux/ux-cli#25]
Hello,
I've been trying out your ux tool and I'm having problems getting past the initial project setup.  I've tried several times and gotten a variety of errors that usually occur during the Installing Bower packages... phase of the setup.  Below is the most recent error I've gotten:

C:\Users\X\Desktop\iservices\ux>ux
{ private: true }
? UI Framework not found. Would you like to install it? Yes
Installing UI Framework...
? ux.json not found. Would you like to create one? Yes
? No styles, scripts, or markup were found. Would you like to scaffold a basic s
? No styles, scripts, or markup were found. Would you like to scaffold a basic s
ite? Yes
? Should Javascript files be processed with Browserify? Yes
? Which JS file is your main (entry) file? scripts/site.js
? Is this a static site? Yes
? Would you like to install any additional libraries?
Installing NPM packages...
Installing Bower packages...
module.js:111
    throw e;
          ^
SyntaxError: Error parsing C:\Users\X\Desktop\iservices\ux\node_modules\@unu
mux\ui-framework\node_modules\browserify\node_modules\browser-pack\node_modules\
umd\package.json: Unexpected token ∩┐╜
    at Object.parse (native)
    at readPackage (module.js:107:52)
    at tryPackage (module.js:117:13)
    at Function.Module._findPath (module.js:183:18)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\X\Desktop\iservices\ux\node_modules\@unu
mux\ui-framework\node_modules\browserify\node_modules\browser-pack\index.js:4:11
)
    at Module._compile (module.js:460:26)
1

**Comment by chuckhendo** [comment]
That's very interesting. Can you tell me the following:

- Version of Windows (and architecure; x86 or x64)
- Version of Node (node -v)
- Version of NPM (npm -v)

**Comment by natewallace** [comment]
Windows 7.1.1.01 Developer-Premium x86
node v0.12.4
npm v2.10.1

**Comment by chuckhendo** [comment]
Alright, I'll set up an image like that and see if I can get it to behave the same way. Thanks for bringing it to my attention

**Comment by natewallace** [comment]
I tried the build tool again but in a different folder and it's working now.  I suspect the encryption software on my computer was the culprit as the errors I was getting involved what looked corrupted or possibly encrypted files.  The new folder that I tried was one that is setup to not be encrypted.  This issue can be closed.
